import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { LayerConflictError, MissingLayerError } from "../errors/cli-errors.js";
import type { CreateSelections } from "../ports/prompt-port.js";

type LayerRegistry = Record<string, Record<string, string> | undefined>;
type LayerStage = "always" | "base" | "frameworks" | "services";
type JsonValue = boolean | JsonObject | JsonValue[] | null | number | string;

interface JsonObject {
  [key: string]: JsonValue;
}

interface ResolvedLayer {
  files: Record<string, string>;
  name: string;
  stage: LayerStage;
}

interface ResolvedLayerSet {
  files: Record<string, string>;
  layers: ResolvedLayer[];
}

interface FileOwner {
  layerName: string;
  stage: LayerStage;
}

const CONFIG_EXTENSIONS = new Set([".json", ".yaml", ".yml"]);
const NONE_VALUE = "None";
const NODE_RUNTIME_LAYER = "base/node-js-typescript";
const STATIC_RUNTIME_LAYER = "base/static";

const FRAMEWORK_LAYER_BY_NAME: Record<CreateSelections["framework"], string> = {
  Express: "frameworks/express",
  None: "frameworks/none",
};

const RUNTIME_LAYER_BY_NAME: Record<CreateSelections["runtime"], string> = {
  "Node.js (TypeScript)": NODE_RUNTIME_LAYER,
  "Static (HTML/CSS/JS)": STATIC_RUNTIME_LAYER,
};

const defaultLayerRegistry: LayerRegistry = {
  always: {
    ".gitignore": "dist\nnode_modules\n.env\n",
    "README.md": "# __PROJECT_NAME__\n\nGenerated by Universe CLI.\n",
  },
  "base/node-js-typescript": {
    Procfile: "web: node dist/index.js\n",
    "docker-compose.dev.yml": [
      "services:",
      "  app:",
      "    image: node:22-alpine",
      "    working_dir: /app",
      "    volumes:",
      "      - ./:/app",
      '    command: sh -c "npm install && npm run dev"',
      "    ports:",
      '      - "3000:3000"',
      "",
    ].join("\n"),
    "package.json": JSON.stringify({
      devDependencies: {
        typescript: "5.9.3",
      },
      name: "__PROJECT_NAME__",
      private: true,
      scripts: {
        build: "tsc -p tsconfig.json",
        dev: "npm run build && npm run start",
        start: "node dist/index.js",
      },
      type: "module",
    }),
    "src/index.ts": [
      'import { createServer } from "node:http";',
      "",
      "const server = createServer((_request, response) => {",
      '  response.writeHead(200, { "content-type": "application/json" });',
      '  response.end(JSON.stringify({ name: "__PROJECT_NAME__", status: "ok" }));',
      "});",
      "",
      "server.listen(3000, () => {",
      '  console.log("Universe app running on http://localhost:3000");',
      "});",
      "",
    ].join("\n"),
    "tsconfig.json": JSON.stringify({
      compilerOptions: {
        module: "NodeNext",
        moduleResolution: "NodeNext",
        outDir: "dist",
        strict: true,
        target: "ES2022",
      },
      include: ["src/**/*"],
    }),
  },
  "base/static": {
    Procfile: "web: npx serve public -l 3000\n",
    "docker-compose.dev.yml": [
      "services:",
      "  web:",
      "    image: node:22-alpine",
      "    working_dir: /app",
      "    volumes:",
      "      - ./:/app",
      '    command: sh -c "npx serve public -l 3000"',
      "    ports:",
      '      - "3000:3000"',
      "",
    ].join("\n"),
    "public/index.html": [
      "<!doctype html>",
      '<html lang="en">',
      "  <head>",
      '    <meta charset="utf-8" />',
      '    <meta name="viewport" content="width=device-width, initial-scale=1" />',
      "    <title>__PROJECT_NAME__</title>",
      '    <link rel="stylesheet" href="./styles.css" />',
      "  </head>",
      "  <body>",
      '    <main class="page">',
      "      <h1>__PROJECT_NAME__</h1>",
      "      <p>Your static Universe project is ready.</p>",
      '      <button id="ping-button">Ping</button>',
      '      <p id="output">Waiting...</p>',
      "    </main>",
      '    <script type="module" src="./main.js"></script>',
      "  </body>",
      "</html>",
      "",
    ].join("\n"),
    "public/main.js": [
      'const output = document.querySelector("#output");',
      'const button = document.querySelector("#ping-button");',
      "",
      'button?.addEventListener("click", () => {',
      "  if (output !== null) {",
      '    output.textContent = "Universe static scaffold is alive.";',
      "  }",
      "});",
      "",
    ].join("\n"),
    "public/styles.css": [
      ":root {",
      "  color-scheme: dark;",
      "  font-family: Inter, system-ui, sans-serif;",
      "}",
      "",
      "body {",
      "  margin: 0;",
      "  min-height: 100vh;",
      "  background: linear-gradient(180deg, #0f172a, #020617);",
      "  color: #e2e8f0;",
      "}",
      "",
      ".page {",
      "  margin: 0 auto;",
      "  max-width: 48rem;",
      "  padding: 6rem 1.5rem;",
      "}",
      "",
      "button {",
      "  border: 0;",
      "  border-radius: 999px;",
      "  background: #38bdf8;",
      "  color: #020617;",
      "  cursor: pointer;",
      "  padding: 0.75rem 1.25rem;",
      "}",
      "",
    ].join("\n"),
  },
  "frameworks/express": {
    "package.json": JSON.stringify({
      dependencies: {
        express: "5.1.0",
      },
    }),
  },
  "frameworks/none": {},
  "services/analytics": {
    "universe/services/analytics.md": "Analytics service selected for __PROJECT_NAME__.\n",
  },
  "services/auth": {
    "universe/services/auth.md": "Auth service selected for __PROJECT_NAME__.\n",
  },
  "services/email": {
    "universe/services/email.md": "Email service selected for __PROJECT_NAME__.\n",
  },
  "services/postgresql": {
    "universe/services/postgresql.md": "PostgreSQL resource selected for __PROJECT_NAME__.\n",
  },
  "services/redis": {
    "universe/services/redis.md": "Redis resource selected for __PROJECT_NAME__.\n",
  },
};

class LayerCompositionService {
  private readonly layers: LayerRegistry;

  constructor(layers: LayerRegistry = defaultLayerRegistry) {
    this.layers = layers;
  }

  resolveLayers(input: CreateSelections): ResolvedLayerSet {
    const resolvedLayers = this.resolveOrderedLayers(input);
    const composedFiles: Record<string, string> = {};
    const owners = new Map<string, FileOwner>();

    for (const layer of resolvedLayers) {
      const fileEntries = Object.entries(layer.files).sort(([leftPath], [rightPath]) =>
        leftPath.localeCompare(rightPath),
      );

      for (const [filePath, content] of fileEntries) {
        const currentOwner = owners.get(filePath);

        if (currentOwner === undefined) {
          composedFiles[filePath] = content;
          owners.set(filePath, { layerName: layer.name, stage: layer.stage });
        } else if (currentOwner.stage === layer.stage) {
          throw new LayerConflictError(filePath, currentOwner.layerName, layer.name);
        } else if (this.isConfigFile(filePath)) {
          const existingContent = composedFiles[filePath];

          if (existingContent === undefined) {
            throw new MissingLayerError(filePath);
          }

          composedFiles[filePath] = this.mergeConfigFiles(filePath, existingContent, content);
          owners.set(filePath, { layerName: layer.name, stage: layer.stage });
        } else {
          throw new LayerConflictError(filePath, currentOwner.layerName, layer.name);
        }
      }
    }

    return {
      files: composedFiles,
      layers: resolvedLayers,
    };
  }

  private resolveOrderedLayers(input: CreateSelections): ResolvedLayer[] {
    const orderedLayerNames = [
      "always",
      RUNTIME_LAYER_BY_NAME[input.runtime],
      FRAMEWORK_LAYER_BY_NAME[input.framework],
      ...this.resolveServiceLayers(input),
    ];

    return orderedLayerNames.map((layerName) => {
      const layer = this.layers[layerName];

      if (layer === undefined) {
        throw new MissingLayerError(layerName);
      }

      return {
        files: layer,
        name: layerName,
        stage: this.resolveStage(layerName),
      };
    });
  }

  private resolveServiceLayers(input: CreateSelections): string[] {
    return [...input.databases, ...input.platformServices]
      .filter((value) => value !== NONE_VALUE)
      .map((value) => `services/${this.toLayerSlug(value)}`)
      .sort((left, right) => left.localeCompare(right));
  }

  private resolveStage(layerName: string): LayerStage {
    if (layerName === "always") {
      return "always";
    }

    if (layerName.startsWith("base/")) {
      return "base";
    }

    if (layerName.startsWith("frameworks/")) {
      return "frameworks";
    }

    return "services";
  }

  private isConfigFile(filePath: string): boolean {
    return [...CONFIG_EXTENSIONS].some((extension) => filePath.endsWith(extension));
  }

  private mergeConfigFiles(filePath: string, left: string, right: string): string {
    const merged = this.mergeValues(
      this.parseConfig(filePath, left),
      this.parseConfig(filePath, right),
    );

    return this.stringifyConfig(filePath, merged);
  }

  private parseConfig(filePath: string, content: string): JsonValue {
    if (filePath.endsWith(".json")) {
      return JSON.parse(content) as JsonValue;
    }

    return parseYaml(content) as JsonValue;
  }

  private stringifyConfig(filePath: string, value: JsonValue): string {
    if (filePath.endsWith(".json")) {
      return JSON.stringify(this.sortJson(value));
    }

    return stringifyYaml(value);
  }

  private mergeValues(left: JsonValue, right: JsonValue): JsonValue {
    if (this.isPlainObject(left) && this.isPlainObject(right)) {
      const merged: JsonObject = { ...left };

      for (const [key, rightValue] of Object.entries(right)) {
        const leftValue = merged[key];

        if (leftValue === undefined) {
          merged[key] = rightValue;
        } else {
          merged[key] = this.mergeValues(leftValue, rightValue);
        }
      }

      return merged;
    }

    if (Array.isArray(right)) {
      return [...right];
    }

    return right;
  }

  private isPlainObject(value: JsonValue): value is JsonObject {
    return typeof value === "object" && value !== null && !Array.isArray(value);
  }

  private sortJson(value: JsonValue): JsonValue {
    if (Array.isArray(value)) {
      return value.map((entry) => this.sortJson(entry));
    }

    if (!this.isPlainObject(value)) {
      return value;
    }

    const sortedEntries = Object.entries(value)
      .sort(([leftKey], [rightKey]) => leftKey.localeCompare(rightKey))
      .map(([key, entryValue]) => [key, this.sortJson(entryValue)] as const);

    return Object.fromEntries(sortedEntries);
  }

  private toLayerSlug(value: string): string {
    return value.toLowerCase().replaceAll(/[.()\s/]+/g, "-");
  }
}

export { defaultLayerRegistry, LayerCompositionService };
export type { LayerRegistry, ResolvedLayer, ResolvedLayerSet };
