const baseStaticLayer = {
  dockerfileData: {
    baseImage: "node:22-alpine",
    devCmd: ["npx", "serve", "public", "-l", "3000"],
    devCopySource: "COPY public public",
    devInstall: "",
  },
  files: {
    ".dockerignore": [".git", ""].join("\n"),
    Procfile: "web: npx serve public -l 3000\n",
    "docker-compose.dev.yml": [
      "services:",
      "  web:",
      "    build:",
      "      context: ./",
      "      target: dev",
      "    ports:",
      '      - "3000:3000"',
      "",
    ].join("\n"),
    "pnpm-workspace.yaml": "",
    "public/index.html": [
      "<!doctype html>",
      '<html lang="en">',
      "  <head>",
      '    <meta charset="utf-8" />',
      '    <meta name="viewport" content="width=device-width, initial-scale=1" />',
      "    <title>{{name}}</title>",
      '    <link rel="stylesheet" href="./styles.css" />',
      "  </head>",
      "  <body>",
      '    <main class="page">',
      "      <h1>{{name}}</h1>",
      "      <p>Your static Universe project is ready.</p>",
      '      <button id="ping-button">Ping</button>',
      '      <p id="output">Waiting...</p>',
      "    </main>",
      '    <script type="module" src="./main.js"></script>',
      "  </body>",
      "</html>",
      "",
    ].join("\n"),
    "public/main.js": [
      'const output = document.querySelector("#output");',
      'const button = document.querySelector("#ping-button");',
      "",
      'button?.addEventListener("click", () => {',
      "  if (output !== null) {",
      '    output.textContent = "Universe static scaffold is alive.";',
      "  }",
      "});",
      "",
    ].join("\n"),
    "public/styles.css": [
      ":root {",
      "  color-scheme: dark;",
      "  font-family: Inter, system-ui, sans-serif;",
      "}",
      "",
      "body {",
      "  margin: 0;",
      "  min-height: 100vh;",
      "  background: linear-gradient(180deg, #0f172a, #020617);",
      "  color: #e2e8f0;",
      "}",
      "",
      ".page {",
      "  margin: 0 auto;",
      "  max-width: 48rem;",
      "  padding: 6rem 1.5rem;",
      "}",
      "",
      "button {",
      "  border: 0;",
      "  border-radius: 999px;",
      "  background: #38bdf8;",
      "  color: #020617;",
      "  cursor: pointer;",
      "  padding: 0.75rem 1.25rem;",
      "}",
      "",
    ].join("\n"),
  },
};

export { baseStaticLayer };
